user:
  name_max_length: 50
  mail_max_length: 255
  pass_min_length: 6
image:
  sign_up_size: 80

gravatar_user_size: 50
per_page_user : 10
remember_me_true: "1"
digest:
  expired_time: 2
limit_size_update_image: 5
size_image_width: 400
size_image_height: 400
post_size: 140
feed_items: 10
microitem: 10
